// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/cli-extension-os-flows/internal/instrumentation (interfaces: Instrumentation)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInstrumentation is a mock of Instrumentation interface.
type MockInstrumentation struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentationMockRecorder
}

// MockInstrumentationMockRecorder is the mock recorder for MockInstrumentation.
type MockInstrumentationMockRecorder struct {
	mock *MockInstrumentation
}

// NewMockInstrumentation creates a new mock instance.
func NewMockInstrumentation(ctrl *gomock.Controller) *MockInstrumentation {
	mock := &MockInstrumentation{ctrl: ctrl}
	mock.recorder = &MockInstrumentationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentation) EXPECT() *MockInstrumentationMockRecorder {
	return m.recorder
}

// RecordCodeAnalysisTime mocks base method.
func (m *MockInstrumentation) RecordCodeAnalysisTime(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordCodeAnalysisTime", arg0)
}

// RecordCodeAnalysisTime indicates an expected call of RecordCodeAnalysisTime.
func (mr *MockInstrumentationMockRecorder) RecordCodeAnalysisTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCodeAnalysisTime", reflect.TypeOf((*MockInstrumentation)(nil).RecordCodeAnalysisTime), arg0)
}

// RecordCodeUploadTime mocks base method.
func (m *MockInstrumentation) RecordCodeUploadTime(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordCodeUploadTime", arg0)
}

// RecordCodeUploadTime indicates an expected call of RecordCodeUploadTime.
func (mr *MockInstrumentationMockRecorder) RecordCodeUploadTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCodeUploadTime", reflect.TypeOf((*MockInstrumentation)(nil).RecordCodeUploadTime), arg0)
}

// RecordOSAnalysisTime mocks base method.
func (m *MockInstrumentation) RecordOSAnalysisTime(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOSAnalysisTime", arg0)
}

// RecordOSAnalysisTime indicates an expected call of RecordOSAnalysisTime.
func (mr *MockInstrumentationMockRecorder) RecordOSAnalysisTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOSAnalysisTime", reflect.TypeOf((*MockInstrumentation)(nil).RecordOSAnalysisTime), arg0)
}
