// Package depgraphpayload mirrors the Go model previously generated by
// github.com/snyk/go-application-framework/pkg/apiclients/testapi for
// io.snyk.api.v1testdepgraph.request.DepGraph and its sub-models.
//
// Upstream replaced the typed model with an opaque DepGraphRef = json.RawMessage
// alias, but this extension still needs strongly-typed access to package
// manager and package metadata (for project name and dependency count), and
// the ability to attach additional top-level fields such as reachabilityScanId,
// ignorePolicy, projectNameOverride, targetReference, target and targetFile.
//
// The struct layout, JSON tags, AdditionalProperties handling, and Get/Set
// helpers are intentionally identical in behavior to the previously generated
// code, so this is a behavior-preserving drop-in for the deleted types.
package depgraphpayload

import (
	"encoding/json"
	"fmt"
)

// DepGraph mirrors the previous testapi.IoSnykApiV1testdepgraphRequestDepGraph
// model.
type DepGraph struct {
	Graph                Graph                  `json:"graph"`
	PkgManager           PackageManager         `json:"pkgManager"`
	Pkgs                 []Package              `json:"pkgs"`
	SchemaVersion        string                 `json:"schemaVersion"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Graph mirrors the previous testapi.IoSnykApiV1testdepgraphRequestGraph model.
type Graph struct {
	Nodes                []Node                 `json:"nodes"`
	RootNodeId           string                 `json:"rootNodeId"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Node mirrors the previous testapi.IoSnykApiV1testdepgraphRequestNode model.
type Node struct {
	Deps                 []NodeRef              `json:"deps"`
	NodeId               string                 `json:"nodeId"`
	PkgId                string                 `json:"pkgId"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NodeRef mirrors the previous testapi.IoSnykApiV1testdepgraphRequestNodeRef
// model.
type NodeRef struct {
	NodeId               string                 `json:"nodeId"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Package mirrors the previous testapi.IoSnykApiV1testdepgraphRequestPackage
// model.
type Package struct {
	Id                   string                 `json:"id"`
	Info                 PackageInfo            `json:"info"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PackageInfo mirrors the previous
// testapi.IoSnykApiV1testdepgraphRequestPackageInfo model.
type PackageInfo struct {
	Name                 string                 `json:"name"`
	Version              string                 `json:"version"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PackageManager mirrors the previous
// testapi.IoSnykApiV1testdepgraphRequestPackageManager model.
type PackageManager struct {
	Name                 string                 `json:"name"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ---------- DepGraph ----------

// Get returns the value of an additional property by name.
func (a DepGraph) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional top-level property.
func (a *DepGraph) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON parses known fields and collects any extras into
// AdditionalProperties so the original JSON shape can be round-tripped.
func (a *DepGraph) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}

	if raw, found := object["graph"]; found {
		if err := json.Unmarshal(raw, &a.Graph); err != nil {
			return fmt.Errorf("error reading 'graph': %w", err)
		}
		delete(object, "graph")
	}
	if raw, found := object["pkgManager"]; found {
		if err := json.Unmarshal(raw, &a.PkgManager); err != nil {
			return fmt.Errorf("error reading 'pkgManager': %w", err)
		}
		delete(object, "pkgManager")
	}
	if raw, found := object["pkgs"]; found {
		if err := json.Unmarshal(raw, &a.Pkgs); err != nil {
			return fmt.Errorf("error reading 'pkgs': %w", err)
		}
		delete(object, "pkgs")
	}
	if raw, found := object["schemaVersion"]; found {
		if err := json.Unmarshal(raw, &a.SchemaVersion); err != nil {
			return fmt.Errorf("error reading 'schemaVersion': %w", err)
		}
		delete(object, "schemaVersion")
	}

	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON emits known fields plus any AdditionalProperties as inline
// top-level keys.
func (a DepGraph) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error

	if object["graph"], err = json.Marshal(a.Graph); err != nil {
		return nil, fmt.Errorf("error marshaling 'graph': %w", err)
	}
	if object["pkgManager"], err = json.Marshal(a.PkgManager); err != nil {
		return nil, fmt.Errorf("error marshaling 'pkgManager': %w", err)
	}
	if object["pkgs"], err = json.Marshal(a.Pkgs); err != nil {
		return nil, fmt.Errorf("error marshaling 'pkgs': %w", err)
	}
	if object["schemaVersion"], err = json.Marshal(a.SchemaVersion); err != nil {
		return nil, fmt.Errorf("error marshaling 'schemaVersion': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- Graph ----------

// Get returns the value of an additional property by name.
func (a Graph) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional top-level property on the inner graph.
func (a *Graph) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *Graph) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["nodes"]; found {
		if err := json.Unmarshal(raw, &a.Nodes); err != nil {
			return fmt.Errorf("error reading 'nodes': %w", err)
		}
		delete(object, "nodes")
	}
	if raw, found := object["rootNodeId"]; found {
		if err := json.Unmarshal(raw, &a.RootNodeId); err != nil {
			return fmt.Errorf("error reading 'rootNodeId': %w", err)
		}
		delete(object, "rootNodeId")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a Graph) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["nodes"], err = json.Marshal(a.Nodes); err != nil {
		return nil, fmt.Errorf("error marshaling 'nodes': %w", err)
	}
	if object["rootNodeId"], err = json.Marshal(a.RootNodeId); err != nil {
		return nil, fmt.Errorf("error marshaling 'rootNodeId': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- Node ----------

// Get returns the value of an additional property by name.
func (a Node) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional property on the node.
func (a *Node) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *Node) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["deps"]; found {
		if err := json.Unmarshal(raw, &a.Deps); err != nil {
			return fmt.Errorf("error reading 'deps': %w", err)
		}
		delete(object, "deps")
	}
	if raw, found := object["nodeId"]; found {
		if err := json.Unmarshal(raw, &a.NodeId); err != nil {
			return fmt.Errorf("error reading 'nodeId': %w", err)
		}
		delete(object, "nodeId")
	}
	if raw, found := object["pkgId"]; found {
		if err := json.Unmarshal(raw, &a.PkgId); err != nil {
			return fmt.Errorf("error reading 'pkgId': %w", err)
		}
		delete(object, "pkgId")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a Node) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["deps"], err = json.Marshal(a.Deps); err != nil {
		return nil, fmt.Errorf("error marshaling 'deps': %w", err)
	}
	if object["nodeId"], err = json.Marshal(a.NodeId); err != nil {
		return nil, fmt.Errorf("error marshaling 'nodeId': %w", err)
	}
	if object["pkgId"], err = json.Marshal(a.PkgId); err != nil {
		return nil, fmt.Errorf("error marshaling 'pkgId': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- NodeRef ----------

// Get returns the value of an additional property by name.
func (a NodeRef) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional property on the node reference.
func (a *NodeRef) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *NodeRef) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["nodeId"]; found {
		if err := json.Unmarshal(raw, &a.NodeId); err != nil {
			return fmt.Errorf("error reading 'nodeId': %w", err)
		}
		delete(object, "nodeId")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a NodeRef) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["nodeId"], err = json.Marshal(a.NodeId); err != nil {
		return nil, fmt.Errorf("error marshaling 'nodeId': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- Package ----------

// Get returns the value of an additional property by name.
func (a Package) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional property on the package entry.
func (a *Package) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *Package) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["id"]; found {
		if err := json.Unmarshal(raw, &a.Id); err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}
	if raw, found := object["info"]; found {
		if err := json.Unmarshal(raw, &a.Info); err != nil {
			return fmt.Errorf("error reading 'info': %w", err)
		}
		delete(object, "info")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a Package) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["id"], err = json.Marshal(a.Id); err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}
	if object["info"], err = json.Marshal(a.Info); err != nil {
		return nil, fmt.Errorf("error marshaling 'info': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- PackageInfo ----------

// Get returns the value of an additional property by name.
func (a PackageInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional property on the package info.
func (a *PackageInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *PackageInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}
	if raw, found := object["version"]; found {
		if err := json.Unmarshal(raw, &a.Version); err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a PackageInfo) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["name"], err = json.Marshal(a.Name); err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}
	if object["version"], err = json.Marshal(a.Version); err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// ---------- PackageManager ----------

// Get returns the value of an additional property by name.
func (a PackageManager) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return value, found
}

// Set stores an additional property on the package manager descriptor.
func (a *PackageManager) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// UnmarshalJSON mirrors the previous code generator's behavior.
func (a *PackageManager) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}
	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}
	return collectExtras(object, &a.AdditionalProperties)
}

// MarshalJSON mirrors the previous code generator's behavior.
func (a PackageManager) MarshalJSON() ([]byte, error) {
	object := make(map[string]json.RawMessage)
	var err error
	if object["name"], err = json.Marshal(a.Name); err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}
	if err := writeExtras(object, a.AdditionalProperties); err != nil {
		return nil, err
	}
	return json.Marshal(object)
}

// collectExtras drains every remaining raw entry in object into dst, allocating
// the destination map lazily, and is shared by every type's UnmarshalJSON.
func collectExtras(object map[string]json.RawMessage, dst *map[string]interface{}) error {
	if len(object) == 0 {
		return nil
	}
	if *dst == nil {
		*dst = make(map[string]interface{}, len(object))
	}
	for fieldName, fieldBuf := range object {
		var fieldVal interface{}
		if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
			return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
		}
		(*dst)[fieldName] = fieldVal
	}
	return nil
}

// writeExtras marshals every entry of extras into the target object map and is
// shared by every type's MarshalJSON.
func writeExtras(object map[string]json.RawMessage, extras map[string]interface{}) error {
	for fieldName, field := range extras {
		raw, err := json.Marshal(field)
		if err != nil {
			return fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
		object[fieldName] = raw
	}
	return nil
}
