// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/cli-extension-os-flows/internal/fileupload/lowlevel (interfaces: SealableClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	lowlevel "github.com/snyk/cli-extension-os-flows/internal/fileupload/lowlevel"
)

// MockSealableClient is a mock of SealableClient interface.
type MockSealableClient struct {
	ctrl     *gomock.Controller
	recorder *MockSealableClientMockRecorder
}

// MockSealableClientMockRecorder is the mock recorder for MockSealableClient.
type MockSealableClientMockRecorder struct {
	mock *MockSealableClient
}

// NewMockSealableClient creates a new mock instance.
func NewMockSealableClient(ctrl *gomock.Controller) *MockSealableClient {
	mock := &MockSealableClient{ctrl: ctrl}
	mock.recorder = &MockSealableClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSealableClient) EXPECT() *MockSealableClientMockRecorder {
	return m.recorder
}

// CreateRevision mocks base method.
func (m *MockSealableClient) CreateRevision(arg0 context.Context, arg1 uuid.UUID) (*lowlevel.UploadRevisionResponseBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevision", arg0, arg1)
	ret0, _ := ret[0].(*lowlevel.UploadRevisionResponseBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevision indicates an expected call of CreateRevision.
func (mr *MockSealableClientMockRecorder) CreateRevision(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevision", reflect.TypeOf((*MockSealableClient)(nil).CreateRevision), arg0, arg1)
}

// SealRevision mocks base method.
func (m *MockSealableClient) SealRevision(arg0 context.Context, arg1, arg2 uuid.UUID) (*lowlevel.SealUploadRevisionResponseBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SealRevision", arg0, arg1, arg2)
	ret0, _ := ret[0].(*lowlevel.SealUploadRevisionResponseBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SealRevision indicates an expected call of SealRevision.
func (mr *MockSealableClientMockRecorder) SealRevision(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealRevision", reflect.TypeOf((*MockSealableClient)(nil).SealRevision), arg0, arg1, arg2)
}

// UploadFiles mocks base method.
func (m *MockSealableClient) UploadFiles(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 []lowlevel.UploadFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFiles", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockSealableClientMockRecorder) UploadFiles(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockSealableClient)(nil).UploadFiles), arg0, arg1, arg2, arg3)
}
